1. Импортируем numpy и прочие используемые в работе библиотеки

In [80]:
import numpy as np
import time
import os

2. Создаем одномерный и двумерный массивы произвольного размера и смотрим на время генерации при помощи numpy и средствами базовой библиотеки

In [25]:
%%time
n = 100*1000
a = np.linspace(0,1,n)
a

Wall time: 2 ms


array([0.00000e+00, 1.00001e-05, 2.00002e-05, ..., 9.99980e-01,
       9.99990e-01, 1.00000e+00])

In [33]:
%%time
r,c=(1000,200)
a = np.linspace(0,1,r*c)
b = np.reshape(a,(r,c))
b

Wall time: 4 ms


array([[0.00000000e+00, 5.00002500e-06, 1.00000500e-05, ...,
        9.85004925e-04, 9.90004950e-04, 9.95004975e-04],
       [1.00000500e-03, 1.00500503e-03, 1.01000505e-03, ...,
        1.98500993e-03, 1.99000995e-03, 1.99500998e-03],
       [2.00001000e-03, 2.00501003e-03, 2.01001005e-03, ...,
        2.98501493e-03, 2.99001495e-03, 2.99501498e-03],
       ...,
       [9.97004985e-01, 9.97009985e-01, 9.97014985e-01, ...,
        9.97989990e-01, 9.97994990e-01, 9.97999990e-01],
       [9.98004990e-01, 9.98009990e-01, 9.98014990e-01, ...,
        9.98989995e-01, 9.98994995e-01, 9.98999995e-01],
       [9.99004995e-01, 9.99009995e-01, 9.99014995e-01, ...,
        9.99990000e-01, 9.99995000e-01, 1.00000000e+00]])

In [26]:
%%time
a = []
for i in range(n):
    a.append(i/100)

Wall time: 40.5 ms


In [47]:
%%time
b=[[]*r]*c
for i in range(r):
    for j in range(c):
        b[j].append(i+j/(r*c))

Wall time: 123 ms


3. Проводим арифметические операции над элементами массивов

In [57]:
c = np.random.randn(10, 10)
d = np.random.randn(10, 10)
print(c[2][3]-d[4][5])
print(c[5][4]*d[8][3])
print(c[3][8]+d[0][0])
print(c[9][6]/d[8][9])

0.8530102460265322
-0.008375548892233804
0.7326699824114886
0.3668290448306046


array([[ 1.15749956,  0.23126811, -0.22662193,  1.3994052 , -0.06060627,
         0.16141652, -0.41837776,  1.40423466,  1.3516373 , -0.44120958],
       [-0.00411273, -0.64386167, -1.80542575, -1.18370303,  0.11550904,
         0.53786942,  0.56330212, -1.91029843, -0.21936081, -0.85601997],
       [ 0.93307549,  1.25385891, -0.98325388, -0.03318309,  1.33859666,
        -0.60641622,  2.40943556,  0.0760501 ,  1.45574492, -1.03612401],
       [-0.83729282, -2.49953164,  0.64652121, -0.97341913, -0.0035478 ,
         1.59248984, -1.75322982,  0.43688   ,  0.89337792,  0.28571083],
       [ 0.84674548, -1.59123407,  1.17782871, -0.59802448, -0.89872124,
         2.20669934, -0.26191554,  1.4948161 , -1.0115906 , -0.97718472],
       [-0.47469583,  0.19567515, -1.26282856,  0.9912037 , -0.04579867,
        -0.66657075,  0.69204973, -1.01593612,  0.79833373,  0.27007385],
       [-0.60402319, -1.5420699 ,  0.44345406,  1.68743281, -0.32990718,
        -0.56237669,  0.01596936,  0.86660668

4. Игра "Жизнь", правильно работает если запускать из командной строки, листинг кода представлен ниже, если понадобятся, файлы игры будут прикреплены в сообщении.

In [81]:
def life_game(x):
    x_forward = np.copy(x)
    while True:
        for i in range(x.shape[0]):
            for j in range(x.shape[1]):
                if x[i][j] == 1:
                    if neighbours_count(x,(i,j)) > 3 or neighbours_count(x,(i,j)) < 2:
                        x_forward[i][j] = 0
                        continue
                    x_forward[i][j] = 1
                    continue
                if neighbours_count(x,(i,j)) == 3:
                    x_forward[i][j] = 1
                    continue
                x_forward[i][j] = 0
        pole_print(x)
        x = x_forward
        end_cond = (np.sum(x) == 0)
        time.sleep(2)
        os.system('cls')
        if end_cond:
            break

In [69]:
def neighbours_count(x, coord):
    area=[[-1 , -1] , [-1 , 0] , [-1 , 1] , [0 , -1] , [0 , 1] , [1 , -1] , [1 , 0] , [1 , 1]]
    count = 0
    if coord[0] == x.shape[0]-1:
        area = [[-1 , -1] , [-1 , 0] , [-1 , 1] , [0 , -1] , [0 , 1]]
    if coord[1] == x.shape[1]-1:
        area=[[-1 , -1] , [-1 , 0] , [0 , -1] , [1 , -1] , [1 , 0]]
    if coord[0] == x.shape[0]-1 and coord[1] == x.shape[1]-1:
        area=[[-1 , -1] , [-1 , 0] , [0 , -1]]
    for i in area:
        if x[(coord[0] + i[0])][(coord[1] + i[1])]:
            count += 1
    return count

In [76]:
def pole_print(x):
    for i in x:
        print("|".join(str(i)))
    print('_'*30)
    

In [74]:
x = np.random.choice((0,1),(25,25))
x

array([[1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
        0, 0, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
        1, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
        1, 1, 0],
       [1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
        0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
        1, 0, 1],
       [0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 1, 0],
       [1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
        1, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 1],
       [0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
        0, 1, 0],
       [0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
        1, 1, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
      

In [82]:
life_game(x)

[|1| |0| |1| |0| |0| |1| |0| |1| |0| |1| |0| |1| |0| |0| |1| |1| |0| |0| |1| |0| |1| |0| |0| |0| |1|]
[|1| |1| |0| |0| |0| |0| |0| |0| |0| |1| |1| |0| |1| |0| |1| |1| |0| |0| |0| |1| |1| |1| |1| |0| |0|]
[|0| |1| |0| |0| |1| |0| |0| |0| |0| |0| |1| |1| |1| |1| |0| |0| |1| |1| |1| |1| |0| |0| |1| |1| |0|]
[|1| |0| |0| |1| |0| |0| |1| |0| |0| |1| |0| |0| |1| |1| |1| |0| |0| |1| |0| |1| |0| |0| |0| |0| |0|]
[|1| |0| |1| |0| |1| |0| |1| |1| |0| |1| |1| |0| |0| |1| |1| |0| |0| |1| |1| |1| |0| |1| |1| |0| |1|]
[|0| |1| |1| |0| |0| |1| |1| |1| |0| |1| |0| |1| |1| |1| |1| |1| |1| |1| |1| |1| |0| |0| |1| |1| |0|]
[|1| |0| |0| |1| |1| |1| |0| |0| |1| |1| |0| |0| |1| |0| |1| |1| |0| |0| |0| |0| |1| |0| |1| |0| |0|]
[|0| |0| |1| |1| |0| |0| |0| |1| |0| |1| |0| |1| |1| |1| |0| |1| |0| |0| |0| |0| |0| |0| |0| |1| |1|]
[|0| |1| |1| |0| |0| |0| |1| |0| |1| |0| |1| |0| |0| |1| |0| |0| |1| |1| |1| |1| |1| |1| |0| |1| |0|]
[|0| |1| |1| |1| |1| |0| |0| |0| |0| |0| |1| |1| |1| |0| |1| |0| |1| |0| |1| |0| |

[|1| |1| |1| |0| |0| |0| |1| |0| |0| |1| |0| |1| |1| |0| |1| |1| |0| |0| |0| |0| |0| |0| |0| |0| |0|]
[|0| |0| |1| |1| |0| |1| |1| |0| |0| |0| |1| |0| |0| |0| |0| |0| |0| |0| |0| |0| |0| |1| |1| |1| |0|]
[|1| |0| |0| |0| |0| |1| |1| |0| |0| |1| |0| |1| |0| |0| |1| |1| |0| |0| |0| |1| |0| |0| |0| |0| |0|]
[|1| |0| |0| |0| |0| |0| |0| |0| |0| |1| |0| |0| |0| |0| |1| |1| |0| |0| |1| |0| |0| |0| |0| |0| |0|]
[|1| |0| |0| |0| |0| |0| |0| |0| |1| |0| |1| |1| |0| |0| |0| |1| |1| |0| |1| |1| |1| |0| |1| |1| |1|]
[|1| |1| |1| |0| |1| |1| |0| |1| |0| |0| |0| |0| |0| |0| |0| |0| |0| |0| |0| |0| |0| |1| |0| |0| |1|]
[|0| |0| |0| |1| |0| |1| |0| |1| |0| |1| |1| |0| |0| |0| |0| |0| |1| |1| |0| |0| |0| |1| |0| |1| |0|]
[|0| |1| |0| |0| |0| |1| |0| |0| |1| |1| |1| |0| |0| |0| |0| |0| |1| |1| |1| |0| |1| |1| |0| |1| |1|]
[|0| |1| |1| |0| |1| |0| |1| |0| |1| |0| |0| |0| |0| |0| |0| |0| |0| |1| |1| |0| |0| |1| |0| |0| |0|]
[|0| |0| |0| |0| |1| |0| |1| |1| |0| |0| |0| |0| |0| |0| |0| |0| |0| |0| |0| |1| |

KeyboardInterrupt: 